name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Node ${{ matrix.node_version }} and ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node_version: [8, 10, 12, 14, 15]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node_version: ${{ matrix.node_version }}
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
